### PR TITLE
feat: Support canceling and reverting service upgrades

### PR DESCRIPTION
**Pull request by StevenChin**
Hey folks,

Found this library pretty useful so I thought I'd contribute! 😁

Let me know if there's anything else I need to do before we can merge the changes.

### CODE REVIEW

**Comment by optii** [comment]
Looks good to me

**Comment by YoannMa** [comment]
Thanks for your contribution, I'll make a release today

**Review by YoannMa — APPROVED** [review]

**Comment by StevenChin** [comment]
Awesome! Appreciate the quick turnaround time guys.

**Comment by YoannMa** [comment]
No problem, we might not use this library in the future as we will move to Rancher 2.

But PR are always welcome.

**Pull request merged**
